# Generated by Django 3.1.5 on 2021-01-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('keywords', models.TextField(blank=True)),
                ('blurb', models.TextField()),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails')),
            ],
        ),
    ]
