# Generated by Django 5.2.8 on 2025-11-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_summaries_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summaries",
            name="blurb",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="summaries",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
