# Generated by Django 5.2.8 on 2025-12-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_alter_summaries_blurb_alter_summaries_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summaries",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
